#pragma once

// serial_api — expose a device's entities on a UART with a self-describing line protocol (AIOT-131).
//
// Enumeration is DERIVED, never listed: the loops over the entity set are generated by including
// esphome/core/entity_types.h (an X-macro guarded per type by USE_*), so a room that gains a relay
// next year exposes it on the next build with no edit here. The prohibition the spec sets is on
// hand-written ENUMERATION — the per-type value adapters below (serial_read_state / serial_domain /
// serial_is_writable) are REQUIRED and are not a violation: ESPHome's per-type accessors are not
// uniform, so one small adapter per supported type is the design. A type with no adapter falls to
// the generic template, which lists it `ro` with no domain and refuses GET with ERR unsupported-type.
//
// SER-1 is the read path. It owns the shared lexer and formatters (serial_api_protocol.*) and every
// read-path response. The write path (SET) is AIOT-133 (SER-2), which extends this same shape.

#include <span>
#include <string>
#include <vector>

#include "serial_api_protocol.h"

#include "esphome/components/uart/uart.h"
#include "esphome/core/application.h"
#include "esphome/core/component.h"
#include "esphome/core/entity_base.h"
#include "esphome/core/version.h"

// Brings the Controller base class and, under USE_CONTROLLER_REGISTRY, ControllerRegistry. Codegen
// (CORE.register_controller()) defines USE_CONTROLLER_REGISTRY and sizes CONTROLLER_REGISTRY_MAX, so
// the registry exists whenever this component is compiled; the guard below only keeps the header
// honest if it were ever compiled without that codegen.
#include "esphome/core/controller.h"
#ifdef USE_CONTROLLER_REGISTRY
#include "esphome/core/controller_registry.h"
#endif

namespace esphome {
namespace serial_api {

// The outcome of reading one entity's state for the wire.
enum class ReadResult : uint8_t {
  OK,           // `out` holds the serialised value
  NO_STATE,     // a button — GET answers ERR no-state
  UNSUPPORTED,  // not one of the eight supported types — GET answers ERR unsupported-type
};

// ---------------------------------------------------------------------------
// Per-type READ adapters. Overload resolution prefers the concrete-type overload over the generic
// template, so a supported type gets its adapter and every other entity_types.h type falls through
// to the template. Each overload is guarded by the same USE_* define that guards the type in
// entity_types.h, so a type the device does not use costs nothing.
// ---------------------------------------------------------------------------

template<class T> inline ReadResult serial_read_state(T * /*e*/, std::string & /*out*/) {
  return ReadResult::UNSUPPORTED;
}

#ifdef USE_SWITCH
inline ReadResult serial_read_state(switch_::Switch *e, std::string &out) {
  out = e->state ? "ON" : "OFF";
  return ReadResult::OK;
}
#endif
#ifdef USE_BINARY_SENSOR
inline ReadResult serial_read_state(binary_sensor::BinarySensor *e, std::string &out) {
  out = e->state ? "ON" : "OFF";
  return ReadResult::OK;
}
#endif
#ifdef USE_SENSOR
inline ReadResult serial_read_state(sensor::Sensor *e, std::string &out) {
  out = protocol::format_state_float(e->state, e->has_state());
  return ReadResult::OK;
}
#endif
#ifdef USE_NUMBER
inline ReadResult serial_read_state(number::Number *e, std::string &out) {
  out = protocol::format_state_float(e->state, e->has_state());
  return ReadResult::OK;
}
#endif
#ifdef USE_TEXT
inline ReadResult serial_read_state(text::Text *e, std::string &out) {
  out = e->state;
  return ReadResult::OK;
}
#endif
#ifdef USE_TEXT_SENSOR
inline ReadResult serial_read_state(text_sensor::TextSensor *e, std::string &out) {
  out = e->state;
  return ReadResult::OK;
}
#endif
#ifdef USE_SELECT
inline ReadResult serial_read_state(select::Select *e, std::string &out) {
  // current_option(), not the deprecated .state (removed in ESPHome 2026.7.0).
  out = e->current_option().str();
  return ReadResult::OK;
}
#endif
#ifdef USE_BUTTON
inline ReadResult serial_read_state(button::Button * /*e*/, std::string & /*out*/) {
  return ReadResult::NO_STATE;
}
#endif

// ---------------------------------------------------------------------------
// Per-type WRITABLE marking for ENT's rw/ro field. The five types the write path (SER-2) actuates
// are rw; the read-only supported types and every unsupported type are ro.
// ---------------------------------------------------------------------------

template<class T> inline bool serial_is_writable(T * /*e*/) { return false; }
#ifdef USE_SWITCH
inline bool serial_is_writable(switch_::Switch * /*e*/) { return true; }
#endif
#ifdef USE_NUMBER
inline bool serial_is_writable(number::Number * /*e*/) { return true; }
#endif
#ifdef USE_TEXT
inline bool serial_is_writable(text::Text * /*e*/) { return true; }
#endif
#ifdef USE_SELECT
inline bool serial_is_writable(select::Select * /*e*/) { return true; }
#endif
#ifdef USE_BUTTON
inline bool serial_is_writable(button::Button * /*e*/) { return true; }
#endif

// ---------------------------------------------------------------------------
// Per-type ENT DOMAIN suffix. Only number, text and select carry one; every other type returns an
// empty suffix (the generic template).
// ---------------------------------------------------------------------------

template<class T> inline std::string serial_domain(T * /*e*/) { return std::string(); }
#ifdef USE_NUMBER
inline std::string serial_domain(number::Number *e) {
  return protocol::format_number_domain(e->traits.get_min_value(), e->traits.get_max_value(),
                                        e->traits.get_step());
}
#endif
#ifdef USE_TEXT
inline std::string serial_domain(text::Text *e) {
  return protocol::format_text_domain(e->traits.get_min_length(), e->traits.get_max_length());
}
#endif
#ifdef USE_SELECT
inline std::string serial_domain(select::Select *e) {
  std::vector<std::string> options;
  for (const char *option : e->traits.get_options())
    options.emplace_back(option);
  return protocol::format_select_domain(options);
}
#endif

// ---------------------------------------------------------------------------

class SerialAPI : public uart::UARTDevice, public Component, public Controller {
 public:
  void setup() override;
  void loop() override;
  void dump_config() override;
  float get_setup_priority() const override { return setup_priority::LATE; }

  // The firmware version the HELLO banner reports. SDK rooms carry their revision in a substitution
  // (not esphome.project), so the module (AIOT-134) threads it in through here. When unset, the
  // banner falls back to the ESPHome framework version rather than being empty.
  void set_firmware_version(const std::string &version) { this->firmware_version_ = version; }

  // Controller callbacks — one override generated per controller-capable entity type. Each forwards
  // to on_entity_update_(), which emits an EVT when subscribed. Buttons have no callback (they have
  // no state), so they never produce an EVT.
  // NOLINTBEGIN(bugprone-macro-parentheses)
#define ENTITY_TYPE_(type, singular, plural, count, upper)  // no controller callback
#define ENTITY_CONTROLLER_TYPE_(type, singular, plural, count, upper, callback) \
  void on_##callback(type *obj) override { this->on_entity_update_(obj, #singular); }
#include "esphome/core/entity_types.h"
#undef ENTITY_TYPE_
#undef ENTITY_CONTROLLER_TYPE_
  // NOLINTEND(bugprone-macro-parentheses)

 protected:
  void process_line_(const std::string &line);
  void handle_list_();
  void handle_get_(const protocol::Command &cmd);
  void handle_get_all_();
  void send_hello_();

  // Write one response line, terminated with '\n'.
  void emit_line_(const std::string &line);

  // The MQTT topic segment, byte-identical to what get_object_id_to() writes.
  std::string object_id_of_(EntityBase *entity);

  // The ESPHome framework version, or the project version when a room declares esphome.project.
  // Used only when no explicit firmware version was configured.
  static std::string default_firmware_version_();

  std::string firmware_version_;

  template<class T> void list_entity_(T *entity, const char *type_name) {
    std::string object_id = this->object_id_of_(entity);
    if (protocol::is_denied(object_id, entity->is_internal()))
      return;
    this->emit_line_(protocol::format_ent(type_name, object_id, serial_is_writable(entity),
                                          entity->get_name().str(), serial_domain(entity)));
  }

  template<class T> void state_entity_(T *entity, const char *type_name) {
    std::string object_id = this->object_id_of_(entity);
    if (protocol::is_denied(object_id, entity->is_internal()))
      return;
    std::string value;
    // A button or unsupported type has no serialisable state; GET * lists states, so skip them.
    if (serial_read_state(entity, value) != ReadResult::OK)
      return;
    this->emit_line_(protocol::format_state(std::string(type_name) + "/" + object_id, value));
  }

  template<class T> void respond_get_(T *entity, const char *type_name) {
    std::string object_id = this->object_id_of_(entity);
    if (protocol::is_denied(object_id, entity->is_internal())) {
      this->emit_line_(protocol::format_err(protocol::err::DENIED, object_id));
      return;
    }
    std::string address = std::string(type_name) + "/" + object_id;
    std::string value;
    switch (serial_read_state(entity, value)) {
      case ReadResult::OK:
        this->emit_line_(protocol::format_state(address, value));
        break;
      case ReadResult::NO_STATE:
        this->emit_line_(protocol::format_err(protocol::err::NO_STATE, address));
        break;
      case ReadResult::UNSUPPORTED:
        this->emit_line_(protocol::format_err(protocol::err::UNSUPPORTED_TYPE, address));
        break;
    }
  }

  template<class T> void on_entity_update_(T *entity, const char *type_name) {
    if (!this->subscribed_)
      return;
    std::string object_id = this->object_id_of_(entity);
    if (protocol::is_denied(object_id, entity->is_internal()))
      return;
    std::string value;
    if (serial_read_state(entity, value) != ReadResult::OK)
      return;
    this->emit_line_(protocol::format_evt(std::string(type_name) + "/" + object_id, value));
  }

  protocol::LineAssembler assembler_;
  bool subscribed_{false};
};

}  // namespace serial_api
}  // namespace esphome
